apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "broker"
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka
      annotations:
    spec:
      #nodeSelector:
      #  kubernetes.io/hostname: k8s-test2-node1
      containers:
      - name: broker
        image: registry.cn-hangzhou.aliyuncs.com/limingmax/mykafka:1.1.4 
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZOOKEEPERS
          value: 192.168.193.1:30201 
        volumeMounts:
          - name: kube-storage
            mountPath: /root/.kube/
        command: ['/bin/bash', '/root/init.sh']
      volumes:
       - name: kube-storage
         hostPath:
          path: /root/.kube/
