kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: default
spec:
  selector:
    app: kafka
    #这个是config里面添加的，也没什么用
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32402
    nodePort: 32402
  type: NodePort
