kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: default
spec:
  selector:
    app: kafka
    #这个是config里面添加的，也没什么用
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32400
    nodePort: 32400
  type: NodePort
